<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="Commands\Orders\CreateOrder\" />
    <Folder Include="Commands\Orders\UpdateOrderStatus\" />
    <Folder Include="DTOs\" />
    <Folder Include="Handlers\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappings\" />
    <Folder Include="Queries\Orders\GetOrderById\" />
    <Folder Include="Queries\Orders\GetOrders\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
